// Platform notes for the changelog page. Each build session appends its
// entry here (newest first); the page merges these with data-derived
// events (sheet approvals, intel arrivals) into one week-grouped feed.
// Convention: date is the ship date (Toronto), title is one line, detail
// is one or two sentences of what changed for the reader.

export interface PlatformNote {
  date: string // YYYY-MM-DD, Toronto
  title: string
  detail: string
}

export const PLATFORM_NOTES: PlatformNote[] = [
  {
    date: '2026-08-06',
    title: 'Deals (Beta) is now the board you signed off',
    detail:
      'The board is rebuilt from the design file rather than from a description of it, which is why it finally looks like the thing you approved. Two typefaces now, one for words and a monospaced one for every number, so a column of amounts lines up down the page instead of wobbling. The text is a lot smaller than before and that is deliberate. The shape changed too. The five stages sit in one row across the top with their file count and their money. Click one and it opens underneath to show the sub-stages inside it, and the files live in those. Only one stage opens at a time, which is the whole trick: the widest thing on screen is five or seven columns instead of twenty-five, so nothing runs off the side. Funded holds sixty-six files and that column scrolls on its own rather than making the page a mile long. Every file card has a colour bar down its left edge and it means one thing: green means this one needs you today, navy means it is under control. Nothing else on the page is green, so you can find your work without reading a word. Two numbers worth knowing. The strip at the top says eighteen closing dates past or inside fourteen days, not sixteen: sixteen have already gone past on files that have not closed, and two more land in the next fortnight. And the colours are your own again. The design file had drifted off your navy and your green because it was drawn from screenshots, so both were taken from the brand values in the codebase instead.',
  },
  {
    date: '2026-08-06',
    title: 'Deals (Beta) looks like the design you approved',
    detail:
      'The blue-grey page is gone, replaced by the warm off-white you picked, and every panel is now white with a hairline instead of a tinted block. The bigger change is the shape. Stages used to run left to right in one long row that ran off the side of the screen by about 588 pixels, which is why there were collapse arrows on every column. Phases now stack down the page, each one with its stages side by side underneath it, and anything empty folds to a single line. Attract, Intake and Monitor are three quiet lines today, and Underwriting and Fulfilment are open with three stages each. Nothing scrolls sideways at any width any more, so the collapse arrows are gone too. A card is four tiers now, split by hairlines: the file reference in blue with the needs-you chip beside it, then the names and the amount, then deal type, address and closing date, then days in the stage on the left and a countdown on the right. A missing amount says No amount in a grey that recedes, rather than showing zero. The countdown is the part worth knowing about. More than two weeks out it is plain, inside two weeks it turns red, and a closing that has already passed on a file that has not closed turns red too. That last one matters: one file has a closing date of 1 April and has been sitting in Application started ever since, and nothing in the system said so before. Funded files are not red, because their closing did not slip, it happened. That leaves 16 red cards instead of 75, which is the whole point of a colour that means something.',
  },
  {
    date: '2026-08-05',
    title: 'The checklist is one line per condition now',
    detail:
      'You said the layout was unreadable, and there was a real reason for it. Every condition was printing twice: once as the condition, then again underneath in grey quotes as the quote from the commitment, because on that file the two are the same words. Twelve conditions were filling twenty-four paragraphs. Now a condition is one line: a status mark, a short name for it, the due date, and one short sentence saying where it stands. Tap the line to open the full wording, the buttons and the details, and the quote only appears there, and only when it actually says something the condition does not. Buttons show on the row you opened, never on all twelve at once. Across the top there are three counts instead of a fraction, collected, outstanding, and needs you, with a thin navy bar under them. Nothing on this screen is red any more. A missing pay stub is work, not an error, so an overdue date reads in navy and a document that failed its check reads in the green that means it needs you. Red is left for the two buttons you cannot take back. Two honest gaps, both named on screen rather than papered over. Nothing writes a short name for a condition yet, so it comes from the document type where the lender named one and from the first line of the wording where it did not. And conditions carry no link to a person on most files, so they sit under General with a line saying why, rather than the page looking like nobody is assigned. Nothing guesses a name out of the wording, because that would put one client on another client\'s row the first time a lender wrote it differently.',
  },
  {
    date: '2026-08-05',
    title: 'The conditions checklist now works the way you do',
    detail:
      'You said the checklist was poor after reading the twelve drafted conditions, and you gave two instructions. Both are in. First, solicitor conditions are out of your way. The checklist leads with broker conditions, the work that is actually yours, in the order the lender numbered them, one to twelve instead of one, ten, eleven, twelve, two. Everything handled at the lawyer’s office sits in its own quieter section below, collapsed with a count, still on the file and still showing its status in case one goes sideways, but no longer dressed as your to-do list. The two conditions the lender did not clearly assign sit in your list wearing an unassigned ownership flag, because something ambiguous belongs where you will see it. Second, you can now knock conditions off one at a time. Every open condition carries a Mark satisfied button, for the moment you have fulfilled it and the lender has accepted it. Press once to arm, press again to commit, exactly like approving terms, and the row locks the moment it lands. The machinery for this already existed and had simply never been given a button. Three things you saw on screen are also fixed. The header no longer says zero open of zero above twelve waiting conditions, it says twelve pending your decision until you approve the list. The numbering sorts as numbers everywhere. And the reject button now looks like what it does: rejecting an extracted set is permanent for that document, the card says so plainly, and the way back is an amendment upload, not another press.',
  },
  {
    date: '2026-08-05',
    title: 'The re-extract preview works now, and the empty checklist explains itself',
    detail:
      'Pressing preview on the re-extract card returned an error instead of the list, because the portal was sending the underwriting system a field it does not accept on a preview. The system refuses unrecognised fields on purpose, as protection, so the fix was ours to make and the preview now sends exactly what is expected and nothing more. The apply path was checked the same way rather than assumed, by probing it against a commitment the system refuses to re-run, where nothing can be written. Separately, the empty Conditions tab used to show one sentence for two very different situations. A file with no commitment still reads upload one. A file whose commitment is on file with its terms approved but no conditions drafted now says what actually happened, the extraction failed, points you to the re-extract card on the Commitment tab, and tells you plainly not to upload the commitment again, because a second upload creates a second document and a second extraction on the same file. That distinction matters because the old wording sent you to ask whether to re-upload, and re-uploading is exactly the churn that once left a file carrying 157 rows.',
  },
  {
    date: '2026-08-05',
    title: 'A failed commitment extraction can now be retried, preview first',
    detail:
      'One file has carried an approved commitment, ten approved terms and an empty conditions checklist since the end of July, because the machine that reads conditions out of a commitment failed once on that document and nothing could ask it to try again short of uploading the document a second time. The Commitment tab on the Beta file page now carries the retry. It works in two steps and the first one cannot be skipped. Preview runs the extraction without writing anything and shows you the full list of conditions it would draft, each with who it belongs to, so you read the twelve before any of them exist. Only after a preview does the apply step appear, and it asks for a typed reason, arms on the first press and commits on the second, exactly like approving terms does. Everything it drafts lands as pending, which means nothing becomes the checklist until you approve the list on the Conditions tab, the same gate every normal upload feeds, and the tab shows an amber count the moment something is waiting there. The ten approved terms cannot be touched by any of this. A re-extraction never overwrites an approved row, so what is already decided is safe from this button by construction, not by care. On a commitment whose extraction already succeeded the system refuses the retry and the card says so in a sentence rather than pretending the button is broken, because re-running a healthy extraction is exactly how one file once ended up with 157 rows. Nothing was applied today. The first real run is yours to press.',
  },
  {
    date: '2026-08-05',
    title: 'Every record in the book now renders somewhere, counted and checked',
    detail:
      'Before you sit down to work through the book by hand, the board had to be able to show you all of it, and until today it could not. The whole book was counted in one pass for the first time: 98 records sit on the board across its phases, 29 sit in the Archive, none are withdrawn, and 33 render nowhere at all, which together is exactly 160. The 33 came in from the migration with no stage recorded, so the board and the Archive had nowhere to put them, and a note at the top admitting they existed also admitted you could not act on them. That note is gone and a fourth view named No stage now sits beside Board, Archive and Withdrawn, carrying its count the same way. Every one of the 33 is listed there with its file reference, its client, its amount where one is recorded, and the same Remove control the other views carry. Nothing was given a stage to make it visible, because writing a stage the file never had would invent a fact about it, and the view says plainly that none is recorded. The file page agrees now too, reading not recorded instead of unknown. Two corrections from the counting are worth knowing. The Archive was reported at 33 in one place and 29 in another, and 29 is the truth. The 33 was always the stageless records, a different group, and none of them are the no-reference records you are clearing. Also, one file reference appears twice in the book, the only duplicate, which is exactly the kind of thing the Remove control exists for. Your withdrawal and restore from earlier today both went through cleanly and that record is back in the Archive where it belongs.',
  },
  {
    date: '2026-08-05',
    title: 'You can take a record out of the book, and a card now opens the file',
    detail:
      'Two changes to Deals (Beta). The first is a Remove control, on every card and at the foot of every file page, for records that should not be in the book at all: a migration artifact, a duplicate, a file that was never real. It does not delete anything, and the wording is careful about that because it matters. The record stays exactly where it is and stays readable. What changes is that a decision is written against it saying you instructed the loader to stop recreating it, and from then on it does. That decision carries your name, the date, and the reason you typed, and the reason is required with no box filled in for you, because in three months the only answer to why a given file went away is the sentence you wrote. It takes two presses, the same as the committed terms buttons: the first arms it and the second commits. Removed records leave the board, the archive and the totals, and gather in a new Withdrawn view beside Archive, which is where you undo one if you get it wrong. Putting a record back needs its own reason too, and it releases the loader to recreate the record on its next run rather than restoring anything by hand. One case is refused outright rather than warned about. Around a hundred records in the book are fed live from Finmo, and removing one stops that feed as well as the loader. On a file that also has an open underwriting file, switching the feed off is a decision that belongs on the file itself rather than on a sweep through a board view, so the control is not offered there at all and the reason is stated in its place. That refusal is enforced on the server, not just by hiding the button. Records that are fed from Finmo but have no open file still show the control, with a warning saying the feed will stop. The second change is smaller and you asked for it: clicking a card on the board now opens the full file directly instead of the preview panel beside the board. The panel was a step between you and the thing you wanted every time. It is still in the code, unused, so it is easy to bring back if you miss it.',
  },
  {
    date: '2026-08-05',
    title: 'The committed terms button now tells you it cannot be undone',
    detail:
      'Approving a commitment’s terms is permanent, and so is rejecting them. There is no undo anywhere in the system, because the gate only ever moves terms that are still waiting, and once they have moved there is nothing left for it to move back. The card never said any of that. It does now, in a line above both buttons, and both buttons carry the word final so it is on the control itself rather than only in the text near it. Nothing about how they work changed: the first press still arms the button and the second one commits, which is how it already behaved. The wording on the second press now says what the press will do rather than just asking you to tap again. One thing worth saying plainly: rejecting is not the safe choice. It is exactly as permanent as approving, and if you reject a set the way back is a new commitment from the lender, not a button here. Separately, a sweep of the Beta file page removed the long dashes from every message on it, because they are not how you write and they were about to be copied into four more tabs that are still being built.',
  },
  {
    date: '2026-08-05',
    title: 'The Beta file page gets Conditions, Commitment and Client',
    detail:
      'Three of the eight tabs on the Beta file page now do something. Conditions shows the same checklist you already work in the Deals file page, and Commitment shows the same upload box and the same ten committed terms with their page numbers and quoted snippets. They are not copies. They are literally the same controls, rendered in a second place, so a fix to one is a fix to both and they can never drift apart and start telling you different things. The numbers agree because they are the same numbers: the file with 157 rows in the database reads 12 on both, because 145 of those rows were retired by later versions of the commitment and are not work anybody has to do. If a commitment ever arrives with terms waiting on your decision, the Conditions tab will carry a small amber count next to its name, so you can see there is something waiting without opening the tab to find out. Nothing is waiting today, so you will not see one yet. The Client tab now lists everyone on the file rather than the first name, with their email, phone, date of birth and the rest of what we hold, and it says which fields we simply do not have rather than leaving a gap you have to interpret. One correction on the Overview: the previous mortgage now says plainly that it is the client’s current one and not this deal’s, because on a file that has not funded yet the old rate was the only rate on screen and that reads the wrong way round. On a file that never had a previous mortgage the block is gone entirely rather than sitting there empty, since empty is supposed to mean not yet.',
  },
  {
    date: '2026-08-04',
    title: 'The terms on a commitment now come to you for a decision, with the document beside them',
    detail:
      'When a lender commitment is read, the ten things that actually matter are pulled out of it: the lender, the amount, the rate, whether it is fixed or floating, the term, the amortization, the payment, the maturity, the prepayment privileges and the penalty. Those now appear in the deal room under Committed terms, and they sit there waiting for you rather than being taken as read. Every one of them shows the exact words the document printed, the page they came from, and the sentence around them, because what you are approving is the document and not somebody summarising it. Where the machine worked something out rather than reading it off the page, that working shows next to the printed words instead of replacing them. The maturity is the one this was built for. That commitment printed 06/10/2031, which could be the sixth of October or the tenth of June, and reading it the wrong way round moves a renewal by four months. So the card shows what was printed, then shows it resolved as 6 October 2031, then tells you how it decided: four other dates in the same document start with a number above twelve, which cannot be a month, so the document writes day first. You can check that reasoning in a second rather than taking it on faith. There is one button, not ten. A commitment is one lender making one offer, so the whole set is approved or rejected together, and if the lender later sends an amendment that comes through as its own set with its own decision. Nothing on the card can be typed over: if a value is wrong the answer is to read the document again, not to correct the record by hand and lose the link back to the page it came from. Only you can make this decision, and that is enforced on our side and again by the underwriting system when the decision is sent.',
  },
  {
    date: '2026-08-02',
    title: 'Deals (Beta): readable projected figures, a real age tile, and a preview panel',
    detail:
      'Three changes. The hatched shading behind projected figures is gone, because you were right that it made the numbers hard to read, and the reason is worth keeping: on your practice history chart the number sits outside the bar so the texture costs nothing, but here it sits inside the fill and the hatch ran straight through the digits. Projected figures are now a solid light green instead, in the BRX family rather than the Fox lime, with the word weighted or projected still beside them so the colour never has to carry the meaning on its own. That creates two greens on one page, so they are kept apart by where they are allowed to appear: the projection green only ever shows in a column footer or the top strip, and the lime that means something needs you only ever shows on a card. They can never sit beside each other, and that is enforced in the code rather than being a thing to remember. Second, the missing deal age figure is back, honestly this time. It could not be built from the created date because every file in the record layer carries the same one, the day the layer was seeded, so it now measures days since a file first moved through a stage. It is labelled for exactly that and says it covers five of the seven files, so a partial average is never mistaken for the whole book. Third, clicking any card now opens a panel beside the board with that file in full: who is on it, what it is for, the amount, the stage and what that stage means, days in stage, who is holding it up, its probability, and every condition on the file. No page load, nothing to edit, and a close button. Opening it costs nothing in page weight.',
  },
  {
    date: '2026-08-02',
    title: 'Deals (Beta) rebuilt: probability, an insights strip, collapsing columns and an Archive',
    detail:
      'The record layer moved again underneath this page, so the page was rebuilt on top of it rather than patched. Advise and Fund are now called Underwriting and Fulfilment, Monitor grew from five steps to seven, and there are twenty-eight stages. None of that needed the page to be told: it reads the names, the steps and the rules from the database every time it loads, which is the thing worth knowing about it. Stages now carry a probability, so each column in Underwriting and Fulfilment shows what that stage is worth after weighting, and there is a strip across the top with your total, what is open, what is closed won, and the weighted pipeline. Every weighted number is drawn on a hatched background, the same way the practice history chart draws the forecast above the funded bars, so a projection can never be mistaken for money you actually have. Intake and Monitor carry no probability at all, because they count people rather than files, and their columns show no weighted figure rather than a zero, since a zero would mean something quite different. Average deal age is deliberately not shown, and the page says why: every file in the record layer carries the same created date, the day the layer was seeded, so any age from it would measure the migration rather than the file. Every column header now has a collapse control, which turned out to be the right answer to a phase that will not fit on one screen: collapse the empty stages and the whole phase fits, and a collapsed column still shows its name, its count and its total. There is also an Archive for files that ended, keeping the outcome visible so lost to another broker reads differently from cancelled. It is empty today.',
  },
  {
    date: '2026-08-02',
    title: 'Deals (Beta) gets the fifth phase, every sub-stage, and colour that means something',
    detail:
      'The record layer moved underneath this page, so the page moved with it. There are five phases across the top now rather than four: Attract has been added in front of Intake, because where people come from is a real part of the business and it was missing. Every sub-stage is on screen whether or not anything sits in it, so Intake shows all seven steps, Advise six, Fund six and Monitor five. That is deliberate. An empty column tells you something and a column that is not there tells you nothing, and you cannot judge a process you can only see half of. Attract is different in kind and is drawn differently: it has sources rather than steps, because nobody moves through a source. Intake and Monitor show their steps with the explanation under each one but no numbers, and say once, plainly, that nobody is placed in them yet. The colour is the other half of this. Your verdict was that the page was plain and bland with nothing separating one stage from another, and that was fair. Each phase now has its own colour family and the columns deepen in that colour as a file moves through the phase, so a glance tells you which phase you are in and roughly how far along without reading a word. Colour is not handed out per stage at random, which is what the other software does and what makes it something you have to memorise instead of something you can read. Purchase, Renewal and Refinance were grey and are now coloured too, since that is a real distinction you read all day. Green still means one thing only, that something is waiting on you, and nothing else on the page is allowed to use it. Columns are wider and the board scrolls sideways rather than squeezing everything onto one screen, because a card you can actually read is worth more than a column you can only count. There is also an Archive now, reachable from the same page, for files that ended. It keeps the outcome visible, so a file lost to another broker reads differently from one that was cancelled, which matters because only one of those is worth contacting again. It is empty today.',
  },
  {
    date: '2026-08-01',
    title: 'A second Deals page, marked Beta, for looking at the new record layer',
    detail:
      'There is a new item under Deals called Deals (Beta). Your real Deals page has not changed at all and is still where you run your day; this one sits beside it so you can look at the shape the business will move to in September and tell us whether it is right before anything commits to it. It reads only. Nothing on it can be clicked to change anything, there is no dragging between columns, and it cannot write even by accident because the connection it uses is only allowed to read. Across the top are the four phases: Intake, Advise, Fund and Monitor. Intake and Monitor are drawn with dashed edges because they count people, and Advise and Fund are drawn solid because they count files and carry a dollar total. That difference is on purpose so the four numbers never read as one pipeline, and the two kinds are never added together anywhere. A dashed line underneath shows renewals coming back in at Advise rather than starting again at the top, because a renewing client takes the strategy session and never needs a discovery call. Advise and Fund show as boards, with a plain sentence under each column heading explaining what that stage actually is. Intake and Monitor say plainly what they are waiting on rather than showing anything invented: Intake needs capture and consent fields that do not exist yet, and Monitor should end up showing the Opportunities engine you already have rather than a second copy of it. Where a figure genuinely is not known, the page says so in words instead of showing a zero. Two files have no stage history recorded and two more have history that stops before the stage they are now in, so those four show no day count at all rather than a number that would look measured and be wrong.',
  },
  {
    date: '2026-08-01',
    title: 'A Tasks page that can hold your whole list, not just the first screen of it',
    detail:
      'There is a new Tasks page beside Today. It shows everything open in four groups, what is overdue, what is due today, what is due in the next seven days, and what has no date at all, with the real number on each heading. That last part matters more than it sounds: the list itself arrives capped at two hundred rows a group, so a page that counted what it had received would tell you two hundred overdue when the truth is nearer three hundred. This one shows the true number, says plainly how many of them it is showing, and gives you a button to pull in the rest. You can complete, put off, or dismiss anything, and add a new one. Putting something off asks for the new date, and dismissing asks why, because a dismissal sticks and the reason is the only record of it. With a backlog this size, doing one at a time is not a plan, so you can tick as many as you like and complete or dismiss the lot in one go, watching it count through them and telling you honestly if any did not take. It is built for a phone first, since that is where you will check it between appointments. Nothing on this page writes to Zoho. Your Zoho task list is untouched and stays the one you run your day from until you decide otherwise.',
  },
  {
    date: '2026-07-29',
    title: 'Lender notes can be written to the Zoho file from the deal room',
    detail:
      'The deal room already had a Generate button that writes a draft you can read and copy out, and that has not changed. What is new sits underneath it: a control that runs the full lender notes generator against the CRM file and puts the finished note in Lender Notes on the Deal itself. It keeps whatever was there before as a history note first, then writes the new one, then adds a short log note recording the run, and it tells you which of those three actually landed rather than just saying it worked. Preview does the whole job and stops before writing anything, so you can read the exact text that would go on the file and then decide. This is the same generator that used to run as an outside automation, now called straight from the portal, so there is one fewer moving part between you and the note. It is admin only, it never appears in demo mode, and it needs two taps to write. If you press it twice inside ten minutes it will tell you it skipped and offer to go ahead anyway.',
  },
  {
    date: '2026-07-28',
    title: 'The booking reminders now run on their own clock',
    detail:
      'The hourly job that sends booking reminders and repairs a calendar entry that failed to write used to be scheduled from an outside automation tool. That schedule had never actually been switched on, which is why no reminder had ever gone out by itself. The schedule now lives in the website itself and runs every hour, so there is nothing to renew and nothing to remember to activate. It is live and was watched doing its first run, which came back clean with nothing waiting to be sent and no calendar entry needing repair. Nothing is needed from you. The old manual trigger still works alongside it, and the outside workflow can simply be switched off whenever it suits.',
  },
  {
    date: '2026-07-28',
    title: 'Your booking hours are yours to change now',
    detail:
      'A new Availability page under System is where you set when the booking pages may offer a time. Weekly hours day by day, with more than one window a day if you want a lunch break. Closed days for holidays, or a day with different hours than usual. Every setting on each of the four kinds of call, the length, the buffers, the notice you need, how far ahead people can book, and how many you will take in a day, each with its allowed range printed underneath. And a list of what is booked ahead, with the client number in front of you and a cancel that sends them the same email and clears the same calendar entry their own cancel link would. Each day and each meeting type saves on its own, so one mistake never blocks the rest. Before this, changing your hours meant changing the database.',
  },
  {
    date: '2026-07-28',
    title: 'The booking pages got their rough edges sanded off',
    detail:
      'Every way the booking flow can go wrong now has its own page instead of a dead end. If the calendar cannot be read, the page says so plainly, offers nothing it cannot keep, and gives both a phone number and an email. Same for a week with no times left, a link that has gone stale, a call that has already happened, and one booked too close to now to move online. The whole flow was also gone over for people using a keyboard or a screen reader, so every box announces its own error and picking a time jumps you straight to the form. Behind the scenes the limits that keep scripts out got tighter and now count by email address as well as by connection, and a calendar entry that fails to write for a full day now emails Michael once a day rather than sitting quietly in a log.',
  },
  {
    date: '2026-07-27',
    title: 'Fox Mortgage has its own booking pages now',
    detail:
      'Clients can pick a time straight on foxmortgage.ca instead of being sent to an outside scheduler. There are four kinds of call to start, a quick discovery call, a full strategy session, a monitoring strategy call, and a signing review. Every one is a phone call where Michael rings the client, so the form asks for a number and the calendar entry carries it. Times come from the real Outlook calendar, so anything already booked is never offered, and each kind of call has its own length, buffer, notice, and daily limit. The page shows times in the visitor own timezone and asks, unticked, whether they are happy to get texts and emails, which is recorded with the moment they said yes. The pages are live but not linked from the menu yet, and the renewal drip still uses the old link until the new one has been through its full test run.',
  },
  {
    date: '2026-07-20',
    title: 'Lender pages get a contacts list you can call or email in one tap',
    detail:
      'Open a lender in the by-lender view and you now see the people you work with there, the BDM and the underwriter, each with a tap-to-call number and a tap-to-email address. Add a new contact, edit one, or retire one who left the desk, all from the page. It is admin only and every change goes through the same audited gate as the rest of the workbench. A lender with nobody saved yet shows a plain prompt to add the first one. The palette also learned two more lenders that were in the rate book but not yet named, so cmd-K can jump to all of them.',
  },
  {
    date: '2026-07-20',
    title: 'Get anywhere fast: search jumps to lenders and pages, and every file ref is a link',
    detail:
      'The search box (press the key with K, or just start typing) now finds more than deals and contacts. Type a lender name and jump straight to its rates. Type a tab name like promos, intel, or bookkeeping and land right on it. Deals were already searchable by file reference or client name, and still are. And everywhere a file reference shows up across the command centre, on the deals list, on the Today page, on the approvals desk, it is now a link straight to that deal room. Getting somewhere stopped being a menu you memorize and became a thing you type.',
  },
  {
    date: '2026-07-20',
    title: 'The Scenario tab describes the deal in one bar, and tells you who it left out',
    detail:
      'The Scenario view no longer buries the answer behind a tall form. You describe the deal in one compact bar across the top, and the matched lenders fill the page below it as the main event. New underneath the matches is a collapsed Excluded list. Open it and every lender that did not make the cut gets one plain line for why, in plain words, like no conventional rate on file, or not available in Ontario, or needs a borrower profile this client does not have. A veteran gets the ranked list at a glance. Anyone newer gets the why. Nothing about how lenders are matched or ranked changed, and typing still only searches when you tab out or press Enter.',
  },
  {
    date: '2026-07-20',
    title: 'Ask Fox stops crashing on a big lender profile, and its errors are honest',
    detail:
      'A lender with a large knowledge profile could crash a whole Ask Fox answer, and the message you got back wrongly said it could not reach the model. The real cause was the profile being cut in the middle and then re-read. That is fixed at the source, the profile is now capped safely, and any single tool that fails can no longer take down the whole answer. The error wording is honest now, in three plain cases: it could not reach the model, the answer was cut off, or the reply could not be read. In every failure case nothing is written, and a reply that could not be read is never shown or saved as a partial answer.',
  },
  {
    date: '2026-07-20',
    title: 'Lenders is one clean tab row now',
    detail:
      'The Lenders page had two rows of tabs stacked on top of each other. Now it is one row: Scenario, Rates, Promos, Intel, Knowledge. The old Lenders and All quotes tabs are folded into Rates behind a By lender / All quotes toggle, so the same rows are one click away either grouped or flat. Nothing moved that you cannot still reach, every old link redirects to its new home, and your saved scenarios still open. Under the hood the rate book now loads once when you open the page instead of being re-read every time you change a scenario input or a dropdown, so the page stops churning as you explore.',
  },
  {
    date: '2026-07-20',
    title: 'Your Microsoft calendar shows up on Today',
    detail:
      'The calendar spot in your day is now live. It reads your Microsoft calendar and lists today’s meetings in Toronto time, in order, with the time, the subject, and where it is or a note that it is online. A meeting that is happening now is marked, and ones that already finished read quietly. It is read only, so nothing here ever changes your calendar. If the calendar cannot be reached, that one card shows a short line and the rest of your page carries on as normal. Nothing else moved.',
  },
  {
    date: '2026-07-20',
    title: 'Check off a task on Today and it completes in Zoho',
    detail:
      'The Tasks card on Today gains a checkbox. Check a task and it marks complete in Zoho, so you can clear your day from the page you already work out of instead of switching over. The tick is instant and settles once Zoho confirms, and for about ten seconds you get an Undo that reopens the task and puts back the status it had before. If Zoho ever does not take the change, the checkbox comes back and one plain line tells you, so nothing ever looks done that is not. Zoho stays the single source of truth for your tasks; the portal is just the remote control. Every complete and reopen is recorded with who did it and when. This is the portal writing to Zoho for the first time, so it is admin only and locked down to a real signed-in session.',
  },
  {
    date: '2026-07-20',
    title: 'Today is now the page you work out of every morning',
    detail:
      'The Home page was rebuilt around one idea: answer three questions in order, what needs me, what is moving, what is at risk. Up top is your day, a live task list beside a spot for your calendar once it is connected. Below it the Waiting-on-you strip, your decision cards, and a single at-risk block that leads with the loudest thing on the page, a file closing this week that still has an overdue condition. Then the renewal nurture progress, one clean table of every deal that is moving with a plain-words next step and how soon it closes, the next thirty days of closings each with a readiness check, and the year with your pace and where money is leaking. Dates now read in plain words everywhere, due today or five days overdue, tinted so the urgent ones stand out, and every file number links straight to its deal room. The old duplicate pipeline table and the stat-tile clutter are gone, so each thing is said once.',
  },
  {
    date: '2026-07-18',
    title: 'The rates scenario stops re-searching on every keystroke',
    detail:
      'A snappiness fix on the Rates scenario view. Typing a mortgage amount or property value used to run a fresh lender search after every single digit, so entering 1,500,000 fired seven searches in a row and made the whole page churn. Now those two fields commit once, when you tab out or press Enter, so you type the whole number first and the results update a single time. Everything else on that view already behaved (the dropdowns and toggles commit on one click, and the command-palette search waits for you to stop typing). Nothing about the results changed, only how often the search runs.',
  },
  {
    date: '2026-07-18',
    title: 'The affordability tool’s bands now read from the client’s whole debt picture (TDS)',
    detail:
      'A small accuracy tweak to the “Can I afford it?” explorer. The three stretch bands (good options / still paths that fit / let us talk this through) now key on the client’s total debt service — the ratio that includes their consumer debts and is the one that actually gates a deal — rather than just the housing ratio. The green “fits comfortably” band still requires both ratios to be inside the standard limits. So a client whose home costs alone look fine but whose overall debt load is high now sees the honest band, and the warmth is unchanged: it still never tells anyone no.',
  },
  {
    date: '2026-07-18',
    title: 'A client’s page can now carry a “Can I afford it?” tool, and it never tells anyone no',
    detail:
      'A new affordability explorer you compose in the deal room and publish to a client’s private page. The client moves four things — the home price, the down payment, the property taxes, and the condo fees — and watches their numbers move in real time, all computed by the same calculator the site’s tools use, never guessed. Below 20 percent down it folds in the default mortgage insurance automatically, and a down payment under the legal minimum shows the number to aim for rather than an error. The result is always one of four warm bands: it fits comfortably, there are good options, there are still paths that fit, or let us talk this one through — because your practice reaches alternative, private, and equity and net-worth lenders that no ratio form can see, so a flat “you do not qualify” would be both wrong and unkind. It never renders a decline, and the words are drafted for your sign-off. On your side, the deal room proposes a baseline from the file (income from the current calculations, the requested rate, the price), you edit any value, and it only shows to the client once you publish it. Unpublishing removes the section. Everything is a frozen snapshot, so a later change to the file never rewrites the panel a client already saw.',
  },
  {
    date: '2026-07-18',
    title: 'Security: every admin data function now needs the operator secret, closing an anon-key gap',
    detail:
      'The key the public forms use to write into our own database was also, quietly, enough to reach every admin data function behind the scenes: someone with it could have forged compliance records, staff provisioning entries, renewal decisions, savings analyses, or impersonation logs, and read the compliance register, the view-as logs, and staff details. Two earlier fixes had closed this for client links and the client presentation layer; this one closes it everywhere else. Every admin-side function now requires a server-held operator secret (the same one already in place, no new setup) and refuses without it, while the parts that must stay open stay open for a stated reason: the client’s own status page (guarded by its private token) and the public form capture. Nothing about how the app works changed for you; the change is entirely under the hood. Note for deploys: because the old un-secured function signatures were removed, the running site’s admin data features are briefly unavailable between applying the database change and deploying the matching code, so the two go together.',
  },
  {
    date: '2026-07-18',
    title: 'A client’s page can now show them scenarios, graded lender options, and a pre-approval letter',
    detail:
      'The private page a client opens from their link grew from status into value, with three things you compose in the deal room and publish only when you choose to. First, scenarios: name a what-if (say a refinance with the car loan paid off, and one without), and the page shows them side by side with the monthly payment and the interest over time, all computed by the same calculator the site’s tools use, never guessed. Second, lender options with a grade you can show them. Pick options from the approved book and each gets a plain A-to-D grade, with the whole scorecard on view: rate is worth 30 points, prepayment and penalty method 20 each, and portability, fees, and flexibility 10 each. The honest part is the point: a part we do not have on file scores nothing and says "not on file", and the letter grade only appears once we have enough on file to be fair, so nothing is ever inflated. Third, the pre-approval letter. On a purchase file you enter the terms and mint a letter the client downloads while it is valid; re-minting replaces the old one, and an expired one tells them to reach out. Nothing sends on its own, nothing shows until you publish it, and unpublishing simply removes it. Also, one quieter fix: the closing date now reads from one source everywhere (the workbench first, Zoho as a fallback), so the deal list, the board, and the client’s own page never disagree about the day a file closes.',
  },
  {
    date: '2026-07-18',
    title: 'A client’s status page now looks right on a laptop, shows their closing day, and lists their documents',
    detail:
      'The private status page a client opens from their link grew up in three ways. First, it is now designed for a desktop, not a stretched phone column: on a laptop the journey gets room to breathe, the documents and team sit side by side, and the type steps up, while the phone view stays exactly as thumb-friendly as before. Second, the closing-day card now shows up. It was missing on live files because the closing date in Zoho was often empty on a refinance while the real date lived in the workbench, synced from Finmo; the page now reads the real date, so a file closing July 28 finally shows "Closing day, July 28, 2026" with a countdown. Third, the documents card became a real checklist. It reads the list of documents Finmo asked the client for and shows a simple progress line ("4 of 19 done") plus three plain states: still needed from you, with each one named in Finmo’s own words and grouped by borrower on a bigger file; received and being looked over, as a count; and done, as a count. It never shows any of our internal notes, verdicts, or flags to a client, and the upload guidance still sits underneath because uploads always go through the secure link.',
  },
  {
    date: '2026-07-18',
    title: 'Clients can hear from you at the moments that matter, and every message waits for your say-so',
    detail:
      'A new comms desk lets the practice keep clients in the loop, in plain words and in your voice, with every single message waiting for you to approve it. The Approvals area gains a Client comms queue: as a file moves along (application received, off to the lender, approved, cleared to close, funded) a short update is drafted for that client, along with gentle document nudges and a review request after funding. Each one shows the full message exactly as the client would read it, grouped by client, so you can approve, tweak the wording, or reject it with a reason. A message whose send date has slipped shows an amber "queued N days ago" so old news is easy to clear. Nothing sends until you flip the master switch on: until then the engine is dark and approving does nothing, on purpose. The switch, the per-client limits, the mailing address the law requires, and the permanent unsubscribe list all live under Settings, and every deal room now shows a quiet record of what has been said to that client and what is waiting. This portal never sends anything itself; it approves, and the workbench sends. The client file page also gains a "Book a time with Michael" link, and a separate security fix locks the private client-link controls behind a server-held secret so the shared key can no longer create or revoke a link on its own.',
  },
  {
    date: '2026-07-18',
    title: 'The documents desk reads each document, and you can approve it or send it back',
    detail:
      'The documents desk now shows what our reader made of each document that arrives. A document that reads clean says "looks right"; one with a real problem, like a pay stub that is too old, is flagged in amber with the reason in plain words and sorted to the top; a scan or photo we could not read says "worth a glance" and sits in its own quiet Questions pile so a stack of blurry ID photos never buries the things that actually need you; and an annual document from last year\'s cycle shows a soft note that a newer one should be available now, without ever calling it a problem. Two new buttons finish the loop. "Check Finmo now" pulls the latest from Finmo on the spot instead of waiting, and tells you when it last checked. And on any document that has arrived you can Approve it or Send it back to the client with a short reason; that is recorded as your review, shown beside the Finmo status and our reading so all three truths sit side by side, and it never changes anything inside Finmo. Two more honest touches: a document request that was deleted in Finmo tucks under a small "withdrawn" line instead of vanishing, and documents that came in without being tied to a request now show in their own "not tied to a request" group so nothing collected is ever invisible.',
  },
  {
    date: '2026-07-18',
    title: 'The documents desk says who approved, and flags documents that have aged',
    detail:
      'Two honesty touches on the documents desk. First, an approval now says where it came from: a document accepted inside Finmo reads "Approved in Finmo", never a bare "Approved" and never "by you", because the desk cannot know which person clicked inside Finmo. Second, documents that go stale with age are now flagged. There is a simple table of how long each kind of document stays fresh, in one place for Michael to adjust: pay stubs 30 days, letters of employment and bank statements 60, benefit statements 90, and the ones whose freshness is really about a tax year or an expiry date printed on the page are left alone for now rather than guessed with a day count. When a document is older than its window the card shows an amber "may be stale" note, moves into the needs-your-look pile, and sorts near the top, without ever hiding that it was approved: both truths sit side by side. And where two people on a file share a first name, the section headers now tell them apart by relationship where the application states one ("Lyntje (spouse)" and "Lyntje (family)").',
  },
  {
    date: '2026-07-18',
    title: 'The documents desk is built around what Finmo asked for, and two live fixes',
    detail:
      'The deal file\'s documents area is now built around the right thing: the document REQUEST. It reads the list of what Finmo asked the client for and reports back, grouped by borrower and by state — what we are still waiting on, what has arrived and needs your look, and what is done. Where our reader has already formed a view on a document it says so on the card, and a flagged item (say a letter of employment dated too long ago) is called out in plain words and sorted to the top. Open a request to see its detail and, where we have it, the read-out of the document with its source. Two things Michael flagged on the live site are fixed alongside: a refinance file no longer shows a purchase price it does not have (it shows the property\'s estimated value from the current application, or nothing, never a stale number), and the ratio and income calculations now show the current figure full-size with older recomputes tucked behind a small "History" toggle, so a superseded number never sits next to the live one. One thing for Michael: renaming the file in Zoho to the main applicant flows straight through to the portal.',
  },
  {
    date: '2026-07-17',
    title: 'A deal file shows its documents at a glance, grouped by what needs you',
    detail:
      'The documents area inside a deal file used to be one long table. It is now a desk of small cards, sorted into three plain groups: what needs your eyes, what we are still waiting on from the client, and what is done. A document that has arrived but has not been looked at sits at the top, where it belongs; a document we asked for but have not received yet shows as a card in its own group so nothing is quietly forgotten. Where the workbench has already read a document and formed a view, the card says so in a few words, whether it meets the requirement or falls short or needs a look, shown as a draft you confirm rather than a verdict. Everything you could do before is exactly where it was: the same uploaders, the same review flow, nothing about how documents are collected or approved changed. This is the same information, laid out so a whole file reads in one look.',
  },
  {
    date: '2026-07-17',
    title: 'Clients can see where their file stands, from a private link',
    detail:
      'The first page built for clients, not staff. Michael can now hand a client a private link that opens a simple status page: where their mortgage is, in plain words, what is happening right now, anything we need back from them, their closing date, and the people on their team with tap-to-call and email. It reads from the same lifecycle the command centre uses, but says it the way a person would, not the way a system does, and it never shows anything about anyone else. Sections only appear when there is something real to show, and a client is never told no on a web page. The link is made and turned off from a card in the deal room, lasts ninety days, and nothing sends on its own yet: Michael copies the link into his own message. A link that is turned off, or expired, or simply wrong all show the same friendly "ask Michael for a new one" page, so the link can never be used to fish for whose files exist. Nothing about a client is ever in the web address itself. Two housekeeping notes shipped alongside: the placeholder Google reviews came off the homepage until there are real ones, and a spot on the old partner sign-up flow that could show a partner name to a stranger was closed.',
  },
  {
    date: '2026-07-17',
    title: 'A new version now actually announces itself',
    detail:
      'The quiet "A new version is ready" toast has been in the portal since Tuesday and has never once appeared, across two deploys. Two reasons, and both had to be fixed. First, the small background program the browser keeps for the app was byte-for-byte identical on every deploy, and a browser decides there is a new version by noticing that file changed. It never changed, so as far as every browser knew, nothing new ever shipped. It now carries the deploy it came from, so each deploy genuinely looks new. Second, nothing ever asked the browser to look. A tab left open all day sat there until the browser got around to its own check, which can take a full day. An open tab now checks a few seconds after it loads, every ten minutes after that, and the moment you come back to the tab. What has not changed is the important part: the page never reloads itself. It waits, offers Refresh, and you decide when. The proof of this one is the next deploy, not this one: leave a tab open, ship, and the toast should find you within about ten minutes.',
  },
  {
    date: '2026-07-17',
    title: 'Client names leave the codebase, and the whole portal speaks one visual language',
    detail:
      'Two finishing sweeps. First, real client names are out of the codebase entirely: every comment, test fixture, config string, and session note now speaks in file references or a small synthetic cast, the standing named exception is retired, and a repo-wide scan holds the line (the testimonials clients approved for the public site stay, and the git-history question is recorded for Michael). Second, the visual language is one system end to end: the remaining admin surfaces (Today below the fold, Approvals, Partners, Compliance, the System pages, Ask Fox, and the deal room interior) moved onto the shared design components, more than two thousand legacy color and font classes became their token equivalents, and the Revenue history chart now draws its projection hatch in calm gray beside solid navy actuals. Lime keeps exactly one meaning: a decision waiting on a human. The decide buttons on the approvals desk, the confirm tap on an Ask Fox card, and the single lime on the Deals list now wear the same decision token as the shell, everything decorative went calm navy or ink, and a test now walks every admin file so a stray decorative lime anywhere fails the build.',
  },
  {
    date: '2026-07-17',
    title: 'One design system, and the menu takes the shape of the lifecycle',
    detail:
      'The sidebar now reads the way the practice works. Eleven working destinations became eight across two honest groups: The book holds the files (Deals, Approvals, and a new Beyond funding page), The practice holds the business around them (Lenders, Revenue, Partners, Compliance), and System keeps the plumbing. The three market pages merged into one Lenders page with Rates, Intel, and Knowledge as tabs, so pricing a deal, checking a sheet arrival, and reading a lender profile stop being three different places. Renewals and Opportunities merged into Beyond funding, the lifecycle phase they always were: one page for everything after a client funds, with the summary strip counting the renewal windows and the opportunity buckets up top, and one nav badge that adds up what the two used to show separately. Bookkeeping folded into Revenue as a tab. Every old link, bookmark, and installed shortcut still works: the old paths redirect permanently to the right tab, and the working sub-pages (the drip queue, the backfill tool, lender detail pages, the bookkeeping queues) keep their own addresses. Under the hood, the design language B2b proved on Deals — the summary tiles, the navy section headers, the tab bar, the status chips, the tabular tables — became shared components the whole portal builds on, and a last set of decorative lime accents went calm so lime keeps meaning exactly one thing: a decision waiting on a human.',
  },
  {
    date: '2026-07-17',
    title: 'Deals becomes the control room: a list-first surface with one lime and a phase-led room',
    detail:
      'Underwriting is renamed Deals (the word Underwriting now means only the lifecycle phase) and the page leads with a list instead of the board: four phase tiles count the book before you read a row, then every live file in closing-date order with its client, phase, lifecycle step in plain words, close date (amber inside 10 days), amount, and a next action that goes somewhere real. Exactly ONE button on the list is lime, on the top-most actionable row, so the eye lands on the single next thing; every other action is a quiet outline, and work the platform cannot do yet carries a small manual chip with the by-hand path spelled out. The board is still there behind a per-user toggle, now four phase columns with navy headers and the two coming-capability cards (application chase, pre-approved and shopping) drawn as dashed placeholders. The deal room goes phase-led: a navy header band with the client name and the Amount and Closes stats, the journey stepper as connected nodes, the current phase open first with its steps and working surfaces, and every other phase collapsed to one honest line. Complete and paid gains its real steps (Broker complete, Compliance package, Paid): the compliance card reads the Zoho compliance status read-only, a rejected package loops back visibly, and Paid shows the recorded commission or says plainly that none is recorded yet. The whole shell now wears the website type pair (Poppins headings, Montserrat body), and the app quietly offers a Refresh when a new version deploys instead of serving stale code. Nothing moved: every file sits exactly where stage truth put it.',
  },
  {
    date: '2026-07-16',
    title: 'Stage truth: the board now positions every card from Zoho',
    detail:
      'The Underwriting board was placing cards by the workbench room state, and nothing updates that state mid-pipeline, so files sat where they entered underwriting instead of where they actually are (one file showed in Intake while Zoho had it approved and clearing conditions). Zoho is the system of record for stage, and now the board acts like it: every card positions by its Zoho stage through the lifecycle mapping, and the rare card with no readable Zoho stage says so plainly ("position from the room, not Zoho") instead of sitting somewhere silently. Six of seven live files moved to their true columns the moment this landed, and the board now shows the real shape of the practice: most live work is at conditions and beyond, not intake. Under the hood, every stage the portal reads is normalized to the picklist display vocabulary, which also cleared the "Ready To Close" unmapped-stage warning: that file now counts in the weighted forecast at the stage weight it always deserved, adding about $475,000 of weighted pipeline with no forecast assumptions changed. The same normalization protects the renewal radar from a funded file slipping out of the pool under its internal stage name.',
  },
  {
    date: '2026-07-16',
    title: 'One lifecycle, spoken everywhere: Intake, Underwriting, Fulfilment, Complete & paid, Beyond funding',
    detail:
      'The pipeline surfaces stop speaking three vocabularies at once. One canonical lifecycle now drives them all: the Underwriting board groups its seven columns under four phase headers (Underwriting runs until a commitment is in hand, so a lender decline loops back through packaging without leaving the phase), the columns themselves got plain-words names (Documents & review, Package & submit, With the lender, Conditions), and the Today pipeline table groups its rows under the same phase names, so the board and the morning view finally read as one system. Every deal room header gains a journey stepper: the five phases in a row with the current one emphasized, and under it the current phase steps in the training-deck words, shaped to the file (a purchase shows the pre-approval letter and shopping steps, a refinance does not). Steps are marked honestly: what the platform does on its own, what Michael does by hand today (hover shows the how, so the dashboard doubles as the standing procedure), and what is coming (application chase reminders, a pre-approved-and-shopping signal, renewal outreach sends). Funded files read Beyond funding and link straight to Renewals. Nothing moved: every file sits in exactly the column and stage it did yesterday, only the headers and labels changed, and a stage the lifecycle does not know renders a loud amber flag instead of being forced into a group.',
  },
  {
    date: '2026-07-14',
    title: 'Underwriting: every file gets its room, automatically',
    detail:
      'The Deals page is now Underwriting, and the gap Michael found is closed: the Today view read the Zoho pipeline while the deals list read workbench rooms, and only three files had rooms. A standing bridge now guarantees that any active file at Submitted or beyond has an underwriting room the moment it needs one — created empty (no evidence, no conditions, no decisions; the work still starts with people), linked to the CRM record, and audited. It runs on a schedule and again every time the page loads, so the board is never stale while you look at it. The page itself is a work queue: five columns from Intake to With lender, each card showing the file, the amount, days without movement, and the next step in plain words; funded and dormant rooms sit behind a toggle, and files still below Submitted appear in a quiet strip above the board with a Start underwriting early action. Files that close in the CRM mark their rooms dormant, never deleted. Test fixtures are now structurally invisible on every live surface.',
  },
  {
    date: '2026-07-14',
    title: 'The Command Centre gets its shell: a calm machine with loud exceptions',
    detail:
      'The whole admin shell is redesigned around one rule: the bright green appears only where a decision is waiting on you. Sixteen flat sidebar items became five groups (Pipeline, Market, Practice, System) with Ask Fox as a persistent button at the bottom; a group shows a green dot when something inside it needs a decision, and badges count decisions, never events. The top of Home is now the Desk: a navy strip that says in one sentence everything waiting on you (rate sheets to approve, flags to resolve, renewals to confirm, files in review), each phrase linking straight to its queue — and when nothing is waiting it says so plainly, because an empty desk is the system working. Under it: up to three decision cards, then every active file with its stage and the next step in plain words. The sidebar collapses to an icon rail that remembers your choice, the notification bell now counts only genuine pending decisions (stale ones mark themselves read — the 88-unread pile is gone), the notification list splits into Decide, Watch, and Log, and search and Ask Fox share one box: anything the search cannot resolve hands to the practice agent as a question. Nothing was removed — every page is where it was, most renamed only where the old name described the plumbing instead of the job (Intel is now Lender intel, Settings is Users & settings). Page interiors are untouched; they adopt the new standards one surface at a time next.',
  },
  {
    date: '2026-07-13',
    title: 'Stage guard hardened, sync-created deals named properly, and no silent stages',
    detail:
      'Michael re-enabled the Submitted stage, and the checks around it found something bigger: Zoho stores two names for several stages (what you read is the display name, what integrations write is the internal one — Conditionally Approved is internally "Application Sent To Lender", and Underwriting In Progress internally carries a double-t typo). The Finmo sync’s stage guard was comparing across those two name spaces, so a hand-set stage like Collecting Documentation could be silently overwritten by an incoming Finmo event. The guard now knows every stage Michael can set, translates what it reads before comparing, and when it meets a stage it does not recognize it preserves the hand-set value and says so on the deal record instead of overwriting. Deals the sync creates are also now born with the book’s naming convention — file reference, em dash, primary borrower — instead of the bare reference Michael had to fix by hand. On the portal, Submitted now carries its own forecast weight (a $359,000 renewal, BRXM-F059751, rides the weighted pipeline at 15%), the funnel renders in true stage order, and any deal volume sitting in a stage the forecast does not know shows as a visible unmapped-stage flag on Home and Revenue rather than quietly counting for zero.',
  },
  {
    date: '2026-07-13',
    title: 'The vanished lenders: a hidden 1,000-row ceiling, found and removed',
    detail:
      'Tonight the Rates page dropped to 11 lender cards and listed quoted lenders like Scotiabank and First National as coverage-pending. No data moved and no deploy caused it: the database service caps every read at 1,000 rows, and the moment the approved-plus-superseded book grew past that (1,765 rows after tonight’s approvals), whole lenders whose sheets were older silently fell off the end of the fetch. The same ceiling was quietly shrinking the Opportunities board — two genuine act-now calls were sitting in stay-put because their best comparables never arrived. Every large read now pages through the full result, so the grid shows all 22 quotable lenders again and the board’s buckets are back to their verified counts. Coverage-pending also means something precise now: a lender appears there only when its newest rates sheet could not be read (a failed extraction or no parser for the format), with the failing sheet named on the chip — old unprocessed history and promo documents no longer count, and a lender with an approved book can never appear there. A live lender whose newest sheet failed gets a small needs-attention badge instead of vanishing. Two smaller things rode along: sheets from lenders the registry says cannot lend in any market the practice serves (the fresh Kootenay sheet loop) now park on a visible shelf instead of refilling the approval queue, returning automatically if the registry ever confirms a serviceable province; and a captured rates sheet the ingest could not attribute to a lender (tonight’s was Alterna Savings) now shows plainly on the Lenders tab instead of disappearing into no bucket.',
  },
  {
    date: '2026-07-13',
    title: 'Every rate carries its term, and the client report is rebuilt around the choice',
    detail:
      'Three corrections, then the new report. First, term honesty: a 1-year rate and a 5-year rate are different products, so every comparable now states its term beside its rate — on the board, in the reproducibility log, and on client documents — and the default comparison must use a rate whose term covers the projection window (the months left on the client’s term for a break, their own term length at a renewal). When only shorter terms exist, the projection stops at the term’s end instead of pretending the rate runs longer, and a deliberately short-term play (a cheap 1-year term with a plan at renewal) is a flagged strategy that takes Michael’s explicit two-tap approval, never an automatic call-list item. Second, a step up to better paper is now always priced as conventional lending: moving to a new lender on better terms is a new application, and the old mortgage’s insurance status never travels with it, so an insured-pricing rate can no longer appear on a graduation flag. Third, the renewal radar’s pools now formally exclude property-tracking rows by name as well as stage, so a property record carrying an amount and a maturity date can never be counted as a mortgage — and the three oldest lapsed entries were confirmed record-by-record to be prior terms of loans whose stories continued elsewhere, listed for Michael to resolve with one tap each. The savings report itself is rebuilt as a three-page document: the choice up front (lower payment, or same payment and mortgage-free sooner), one clearly dated rate with its term and never the lender’s name in writing, a side-by-side table of where each path stands by the end of the window, the penalty stated as a minimum with the break-even figure drawn on a gauge, and next steps framed as conditions rather than verdicts — because on a fixed rate, only the lender’s payout statement can decide it.',
  },
  {
    date: '2026-07-13',
    title: 'Paper grades, renewals the CRM missed, and the desk override',
    detail:
      'Three additions to the Opportunities engine. First, every lender now carries a paper grade — A, B, or private — and a monitored mortgage prices only against its own grade: a $1.29M private-paper file at 9.99% and a $1.35M alternative-program file were both being compared against prime monoline rates, which manufactures savings those clients may not qualify for. B paper now prices against the B book, private paper is honest about the book carrying nothing comparable, and a possible step up to better paper shows as a flagged opportunity with the rate and sheet date only — Michael assesses qualification, and pricing it on a client report takes his explicit two-tap approval, recorded. A mortgage whose lender the map does not know, or whose rate does not fit its mapped grade, routes to review rather than trusting the map. Second, the radar now catches renewals Zoho never heard about: when the monitoring feed shows a mortgage that started well after the deal closed, or a different lender or rate, the file moves to an appears-renewed section with both sides of the evidence, held out of the call pools until Michael confirms it (one click records Renewed With Us, the picklist value that arrived today) or clears it with a reason. Live, that finds five of the eight action-window files and six of the eighteen lapsed ones. Third, Michael can now override the comparison on any file: pick a different approved eligible quote, or enter a desk rate he was quoted directly with its source and a mandatory reason. Every override is recorded as a documented suitability decision, shows on the board and on the report as his call, and the report frames a desk rate as a direct quote, never a sheet rate. The savings log is also now append-only by database triggers, not just permissions, and dollar-one placeholder rows can no longer offer their garbage into the CRM.',
  },
  {
    date: '2026-07-13',
    title: 'Savings analysis: honest penalties, like-for-like comparisons, and a reproducible record',
    detail:
      'Three corrections land together. First, the client savings report stops concluding on the penalty floor: three months of interest is the minimum a fixed-rate penalty can be, and on a fixed mortgage priced above today’s market the interest rate differential is usually the larger figure that actually applies. For every fixed-rate break the report now states the minimum in that word, states the break-even penalty — the single number that decides whether the switch pays — and draws no conclusion until the real penalty is in hand, because knowing how a lender calculates its penalty is not the same as knowing the figure. Where the method is on file Michael estimates it on the call; either way the lender confirms the exact amount before anything moves. Second, the comparison itself is now like-for-like: a fixed client is compared against the best fixed rate, a floating client against their own kind, because a lower floating rate shown to a fixed client is not savings, it is rate risk the client does not carry today (on the proving file, $244.12 a month of true relief against a floating option showing $409.84 — the extra $165.72 is exposure, about $64 a month per quarter-point prime move). The cheaper cross-family option still shows, clearly labelled with a plain-language risk line, and recommending it on a client document takes Michael’s explicit two-tap approval, recorded. Floating rates also now rank on the effective rate computed from each lender’s own prime, never on the discount alone — a deep discount off a credit union’s higher internal prime is not a better rate. Third, every savings analysis that reaches the board or a client document now writes one append-only log row with the calculation version, a fingerprint of every input, the quotes used with their sheet dates, and the figures rendered, so any document handed to a client can be reproduced exactly, later, by anyone.',
  },
  {
    date: '2026-07-13',
    title: 'Backfill: a shared email can no longer write the wrong mortgage’s dates',
    detail:
      'Six people in the monitoring export hold more than one mortgage and carry the same email on every row. The Zoho backfill matched each mortgage to a contact by email, so both mortgages resolved to the same person and each proposed its own maturity date and rate into that person’s records — the system built to repair a wrong date was the one most likely to overwrite it with the other mortgage’s. A match is now a pair, the contact AND the specific mortgage, never the contact alone. When several export mortgages share an identity, the contact’s deals are attributed by evidence: the property address first, the amount second, and a deal that no mortgage — or more than one mortgage — can claim is contested and nothing is proposed into it. Contested deals land on a needs-manual-match card showing every claimant mortgage with its address, amount, and maturity beside each candidate deal, and Michael picks which record belongs to which mortgage; the pick is recorded in the backfill audit as his decision, and the server still refuses to fill anything but a field that is empty at write time. Against the live export, six shared-identity groups covering thirteen of the forty-one mortgages now route through this path instead of proposing automatically.',
  },
  {
    date: '2026-07-13',
    title: 'Opportunities: the stated payment is now the client’s actual payment',
    detail:
      'The savings analysis was deriving a client’s current payment by re-amortizing today’s balance over the original amortization period, which understates the payment on every seasoned mortgage (on a two-year-old $500,000 file at 5.50%, by $121.37 a month). A client knows what leaves their account, so this is the error a client catches. The payment now reconstructs the original schedule — the original amount over the original amortization — and the comparison prices the new rate over the months the client actually has left, which the analysis now carries. A new reconciliation gate defends every figure: the balance is modeled forward from origination and compared to the monitoring feed, and when the two disagree by more than half a percent the analysis is blocked into a Needs-review bucket on the board showing both figures and the drift, because prepayments, adjustable-rate changes, and bad vendor data all look exactly like this. A blocked file’s savings report states no figure at all, not even the balance, until Michael confirms the true position with the lender. Against the live export, 25 of 41 mortgages reconcile to a median drift of two hundredths of a percent, and 14 route to review — most consistent with accelerated-payment clients whose real payment genuinely differs from the monthly schedule, which is precisely why an unreconciled figure is never stated. The golden test set now carries a seasoned fixture where the wrong and right methods diverge, alongside the unseasoned commitment anchor where they agree to the cent.',
  },
  {
    date: '2026-07-13',
    title: 'One classifier: the portal reads eligibility straight from the workbench',
    detail:
      'The workbench finished classifying the rate book (947 of 949 approved quotes now carry their eligibility columns; the only unclassified rows are test artifacts), so the portal deleted its copy of the classification rule and reads the columns directly. One classifier now lives in one place, in the workbench, where the sheets are extracted. The fail-closed rule got stricter with it: a quote the workbench has not classified yet, which is exactly what a fresh arrival from the intel pipeline looks like, is treated as carrying an undisclosed restriction. It is excluded from default results, visible under show-restricted with a plain not-yet-classified note, and it can never reach a client document, not even pinned, because a restriction nobody can name is a restriction nobody can confirm the client meets. Re-running the monitoring export under the new reads reproduced every outcome exactly, which is the point: same answers, one source.',
  },
  {
    date: '2026-07-12',
    title: 'Lender eligibility, client constraints, and the cost of a preference',
    detail:
      'Two British Columbia credit unions were leading Ontario rate results. Kootenay Savings holds the deepest floating discount in the book, so it won the top slot on almost every floating scenario, and the Opportunities engine proposed it as a real client’s best comparable. It cannot do an Ontario deal. Now every surface that ranks a lender filters for structural eligibility first: the subject province governs (Ontario is the default and the only one today), an ineligible lender is excluded not deprioritized, and a lender whose provincial availability the workbench has not confirmed shows internally with an availability-not-confirmed flag and never on a client document. Program eligibility bites harder: the entire sub-four-percent ladder that was ranking as available is physician-only, banking-bundle-only, or exclusive-channel, so it hid the real best rate an ordinary borrower can genuinely have. The default results are now only what the client can definitely have, with qualifier toggles (physician, high net worth, business for self, new to Canada, willing to move banking, quick close) that unlock restricted rates, a show-restricted view that reveals them each carrying its requirement in a plain sentence, and a manual pin that records a confirmation before a restricted product can reach a client. Transaction type now determines product class: a monitoring client who breaks their mortgage is a refinance, which is uninsurable and priced against conventional rates only, with an eighty-percent loan-to-value hard cap and a requalification line on every card and client page. Re-running the monitoring export, twenty of forty-one opportunities changed bucket once conventional pricing, the cap, and eligibility were applied. Client lender constraints arrived as a first-class feature: per-client rules (exclude a lender, require one, prefer one), each with a required reason, kept with their history and never deleted, and the cost of the preference computed by the shared engine. A client choosing a lender for a stated reason with the cost quantified is the documented suitability assessment a regulator asks for, and it now counts on the deal room’s compliance card. Ask Fox inherited all of it: its rate tool returns eligible lenders only and it will not quote an unconfirmed one to a client. The savings and rate comparison documents withhold any lender whose province is not confirmed. The count of unconfirmed lenders is on the Rates page so the gap gets filled.',
  },
  {
    date: '2026-07-12',
    title: 'Opportunities: the Strategic Mortgage Monitoring engine',
    detail:
      'The monitoring service watches every enrolled mortgage and mails a savings figure; until now that intelligence lived in a monthly spreadsheet nobody worked. Opportunities turns the export into a pipeline. Upload the CSV and every raw row is captured first, before any parsing can fail, then parsed: money and percents read cleanly, a dash stays uncomputed and never becomes a zero, dollar-one placeholder rows are flagged not analyzed, co-borrowers collapse to one mortgage keeping every borrower, and lender names normalize to the book. Beside the service’s own figure the portal shows Fox’s independent analysis: the best gate-approved comparable with its sheet date, the payment change from the validated engine, the early-break penalty framed honestly (three months’ interest for floating; for fixed, the greater of that and the rate differential, with the lender’s method named or the gap stated), the break-even, and a net benefit after the penalty. That net benefit buckets the board — act now, marginal, stay put, insufficient — ranked by dollars, so the call list is ordered by what it is worth. The honest half matters most: a client on a low rate near maturity is told to WAIT, never sold a switch that costs more than it saves, and where the two figures disagree the disagreement is shown. One tap opens the priced scenario, preps a call, or downloads a grade-six savings report (compensation scrubbed from every line, wait-for-maturity framing where it applies). A backfill tool matches each file to Zoho by email, then phone, then name, and proposes filling only the EMPTY maturity dates and rates the export knows and the CRM does not — each a confirmation approved one at a time or all at once, every write recomputed server-side and recorded; conflicts are shown, never overwritten. On Renewals, the lapsed alarm now reconciles against the export: still-with-lender past maturity is a recoverable auto-renewal and the highest-value call on the board, lender-changed is flagged as won-or-lost-unknown, and a retention signal is computed. Home gained an act-now opportunities line. Verified against the live export: 41 mortgages from 49 rows, one placeholder caught, zero parse failures, zero unmapped lenders, and a client’s 1.99% file (IFMS-F001515) correctly told to wait with its maturity and rate proposed as backfills.',
  },
  {
    date: '2026-07-12',
    title: 'The Renewal Radar: no renewal slips again',
    detail:
      'The practice was losing renewals silently. The renewal automation that was designed with a 150-day lead and a six-email drip has never fired on a single deal, so funded mortgages were maturing with no contact and no record. A new Renewals section reads every funded deal by maturity window and makes the failure impossible to miss. Lapsed is an alarm, not a status: 18 funded files worth $11.0M matured with no recorded outcome, sorted by amount, in red that cannot be collapsed away. Eight files worth $4.37M mature before year end and are actionable now. Six funded deals have no maturity date at all and are invisible to the whole system until it is backfilled, so they sit in their own block at the top that persists until it is empty. Every card carries the payment-shock preview, the reason a client answers the phone: the file rate against the best approved fixed rate today with its sheet date, and the monthly payment change from the validated engine, honest where the current rate is not on file. One tap preps an Ask Fox call brief; the status actions (contacted, in discussion, application sent, renewed elsewhere, no longer needs, unreachable) write to Zoho through the same confirmed-action path the agent cards use, each an enumerated choice recorded with who and when. Home gained a lapsed-renewal alarm, an action-window count, a missing-maturity count, and a compact five-number strip; the bell fires when a renewal crosses into the action window and when one lapses. Revenue restored its practice KPIs (funded all time, average deal, best year, years active) alongside the renewal book, a number the practice had never seen: $17.95M under management, $7.71M maturing in the next year. Every figure reconciles to the corrected pipeline data. One honest gap found and reported: Zoho has no picklist value for a renewal won with us, so a retention cannot be recorded until that value is added.',
  },
  {
    date: '2026-07-12',
    title: 'Pipeline truth, and the Practice History chart',
    detail:
      'The pipeline was counting things that are not deals. Forty-nine property records sat in an Additional Properties stage, and two dozen dead files from 2021 and 2022 sat open in Options and Pending, never closed and never marked lost. Together they inflated every open-pipeline figure and, worse, flipped goal pacing to read ahead of target when the true position was behind. The fix is a self-defending pipeline: property records stay out by stage, and any open file whose close date is more than 90 days past, or that has sat open more than 180 days without moving, drops into a visible, groomable stale bucket on Revenue that links straight to Zoho. Nothing is deleted; groom a file and it leaves the bucket on the next read. The active pipeline now reconciles to 8 real files worth $4.71M, the weighted pipeline fell from $4.14M to $2.19M, and the pace reads honestly behind. Both funded stage names are covered everywhere ("Mortgage Funded" for the history, "Funded" for 2026), and one investor-page filter that missed one of them is fixed. The Practice History chart is also back on Revenue: funded volume by year from 2021 with deal counts on every bar, the current year split into funded-to-date solid and the weighted pipeline stacked above it as a hatched projection so a forecast is never read as an actual, the three 2026 milestones marked plainly at the right edge, and no trend line pretending the automation has moved numbers it cannot have moved yet. A one-tap export renders it as a slide-ready image in the house style with the Fox mark, for the room of mortgage professionals it was built for.',
  },
  {
    date: '2026-07-11',
    title: 'The offers desk: promotional offers become approvable',
    detail:
      'Twenty-three lender promos were waiting in a terminal for approval; now they sit on the desk. A new Offers tab on Approvals decides each one with a two-tap approve or reject that flows through the audited gate under your name, and each card shows the offer priced as identity, the extraction evidence with page citations, the conditions verbatim, and — the field that matters most — the window, rendered loudly. Nineteen of the twenty-three had no stated end date, so every one of those now carries an unmissable warning that it will not retire on its own and must be confirmed before quoting, on the desk and everywhere the offer appears afterward. Once approved, an offer lands on the Promos board with its full detail, matches a scenario permissively where its eligibility could not be read (and says so), sorts first when it beats every sheet quote, and can be pinned into a client PDF with its conditions and expiry — never its compensation. Pending offers also join the Home attention rail and the notification bell.',
  },
  {
    date: '2026-07-11',
    title: 'Lender logos are live',
    detail:
      'Thirty-three lender logos are now dropped in, so nearly every lender shows its real mark across Rates, Knowledge, Intel, and the approvals desk instead of a monogram. Lenders without a logo keep the on-brand monogram, and any logo added later appears on its own with no code change.',
  },
  {
    date: '2026-07-11',
    title: 'Rates v3: tabs, lender browse, logos, and the promos board',
    detail:
      'Rates is now four tabs. Scenario still answers who wins a deal and stays the default (the find-rates button from a deal room lands here with its file banner), and its lender cards now open with an unmistakable click — a pointer, a hover lift, a chevron, and a drill-in that scrolls to the top. A new Lenders tab browses the whole approved book with no scenario: each lender shows its best rate per product class and its deepest floating discount (adjustable and variable kept apart, never one misleading lowest number), and the cards group into three honest states — live, awaiting your approval (links to the sheets queue), and coverage pending (a sheet was captured but its format has no parser yet). A new Promos tab is the offer book on its own board, soonest to expire first, each card citing the announcement it came from. Every lender now carries a mark: a real logo the moment one is dropped into public/lenders/, an on-brand navy-and-lime monogram until then, shown everywhere a lender is named. Michael can name and save the scenarios he runs often and recall them in a tap. And the client rate PDF is now guarded by a test that proves it never shows lender compensation to a borrower.',
  },
  {
    date: '2026-07-10',
    title: 'Session 9: The finale — an app, a bell, a search bar, and a demo',
    detail:
      'The command center becomes an installable app. Add it to your home screen from admin or a partner portal; a security-first service worker caches the shell and static assets but never a page or an API response carrying client data, and an offline screen stands in when you lose signal. A notification bell now gathers five kinds of signal the portal already computes — new rate sheets to review, sync-freshness alarms, form-intake failures, credential renewals entering the 60- and 14-day windows, and gate decisions made from the command line — so the desk and the terminal are one world; each category is a toggle, per-user read state is remembered, and nothing replaces the existing emails. Press ⌘K anywhere to search deals, contacts, partners, lender knowledge, and the navigation itself, grouped and keyboard-driven, honest when a source is slow. And a new admin-only demo mode swaps the whole platform to believable fictional data — zero real clients on screen, every write disabled — so the command center can be shown to a prospect with nothing real exposed. The finale sweep retired the last mock pages and the dormant daily-briefing email (the Home rail serves it live now), made the partner portals fully responsive, and marked the original nine-session map complete.',
  },
  {
    date: '2026-07-10',
    title: 'Session 8: Multi-user hardening',
    detail:
      'The platform is ready for its second human before the second human exists. Roles are live and verified: ops, underwriting reviewer, and agent each see exactly their surface, every admin page gates on a permission key, and Settings gains an effective-access view (pick a role, see everything it reaches). View-as is now a governed capability: a picker under the portals nav, structurally read-only (controls absent, server refuses writes), every session logged with viewer and viewed under Audit Log. Provisioning is a wizard at Settings → People — staff, partner (Zoho id picked, never typed), and agent (workbench half through the Gates API with its honest setup checklist). Offboarding is one two-tap action: access disabled and sessions revoked immediately, with a persisted cleanup checklist built from what the system knows. Nothing deletes.',
  },
  {
    date: '2026-07-10',
    title: 'Session 7: Revenue and Partners',
    detail:
      'The money layer and the relationship layer. Revenue: commission forecast by close month (stage-weighted, priced from recorded commissions where they exist and the comp model everywhere else, every estimate labeled), funded trends with honest mix charts, the conversion funnel with its method caveat, goal pacing deep view, and the business-line P&L tile with its honest not-connected state. Partners: ranked for Monday attention with health chips, referral stats, attributed revenue, and portal sign-in recency; detail pages gain referred files and cadence. Ask Fox learned to check open Zoho tasks before proposing a card (prompt v2), and the chat gained a thinking indicator.',
  },
  {
    date: '2026-07-10',
    title: 'Ask Fox: the practice agent',
    detail:
      'A chat in the sidebar that preps and reviews calls from the systems the portal already trusts: Zoho records, the gate-approved rate book, lender knowledge with its as-of dates, and the workbench file where one exists. Every number carries its source, gaps say not captured, and CRM changes only happen through confirm cards you tap. Decisions stay on the Approvals desk. Add ANTHROPIC_API_KEY in Vercel to switch it on; rubric v1 and the system prompt are versioned in the repo.',
  },
  {
    date: '2026-07-10',
    title: 'Session 6: floating rates on screen, and Compliance',
    detail:
      'Adjustable and variable rates now render as what they are: discount first, with the effective rate computed against the served prime and labeled with its date. Cash back tiers are their own rows with the printed conditions, promo offers appear inside matching scenarios, and the approvals cards print floating sheets correctly. New Compliance module: credential renewals on the attention rail, the complaint and incident register, and a versioned policy library with acknowledgments. Nothing in it ever deletes.',
  },
  {
    date: '2026-07-10',
    title: 'Session 5: Rates becomes a scenario tool',
    detail:
      'Describe the deal and see which lenders win it, lowest rate first, from sheets Michael approved through the audited gate. Drill into products with full provenance, pin up to three to compare, and download a client-ready PDF. Deal rooms gain a find-rates button. The dense table stays behind a toggle.',
  },
  {
    date: '2026-07-09',
    title: 'Session 4: Knowledge, Rates, Intel, and the reference layer',
    detail:
      'Lender knowledge base with as-of dates and stale flags, the rates browser with superseded history, promo countdowns, the intel feed, conditions decisions in the deal room, terminal files out of the attention rail, and this changelog.',
  },
  {
    date: '2026-07-09',
    title: 'Session 3: the desk goes live',
    detail:
      'Approvals desk with four decision queues through the Gates API, deals list and deal room, the audit viewer with CSV export, and the database-enforced read-only posture (service key removed).',
  },
  {
    date: '2026-07-09',
    title: 'Session 2: the Gates API (workbench repo)',
    detail:
      'Every portal decision now flows through the fox-underwriting Gates API with the authority matrix enforced server-side and full audit identity.',
  },
  {
    date: '2026-07-09',
    title: 'Session 1: the command center foundation',
    detail:
      'Admin shell and navigation, the exception-first Home, Status page, authority matrix, and read-only workbench wiring.',
  },
]
